//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR_Assignment1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class team
    {
        public int team_id { get; set; }
        public string team_name { get; set; }
        public Nullable<int> team_wins { get; set; }
        public Nullable<int> team_losses { get; set; }
        public Nullable<int> team_rank { get; set; }
        public Nullable<int> team_number_of_games { get; set; }
        public Nullable<int> team_week_number { get; set; }
        public string team_oponent { get; set; }
        public Nullable<int> team_oponent_wins { get; set; }
    }
}
